# ============================================
# RENDER.YAML - Backend Deployment Config
# SAP Technologies API Server
# ============================================

services:
  # Backend API Service
  - type: web
    name: sap-technologies-api
    env: node
    region: oregon # Choose: oregon, frankfurt, singapore, ohio
    plan: free # or starter ($7/month), standard, pro
    branch: main
    buildCommand: cd server && npm install
    startCommand: cd server && node src/app.js
    healthCheckPath: /api/health
    
    # Environment Variables (SET THESE IN RENDER DASHBOARD)
    envVars:
      - key: NODE_ENV
        value: production
      
      - key: PORT
        value: 5000
      
      - key: MONGODB_URI
        sync: false # Set in Render dashboard
      
      - key: SESSION_SECRET
        generateValue: true # Auto-generate secure secret
      
      - key: GMAIL_USER
        sync: false # Set in Render dashboard
      
      - key: GMAIL_PASS
        sync: false # Set in Render dashboard
      
      - key: NOTIFY_EMAIL
        sync: false # Set in Render dashboard
      
      - key: WHATSAPP_ENABLED
        value: true
      
      - key: WHATSAPP_ADMIN_NUMBER
        sync: false # Set in Render dashboard
      
      - key: WHATSAPP_SESSION_PATH
        value: ./whatsapp-session
      
      - key: CORS_ORIGIN
        sync: false # Set to your Vercel frontend URL
      
      # Optional: SMS Service
      - key: AFRICAS_TALKING_USERNAME
        value: sandbox
        sync: false
      
      - key: AFRICAS_TALKING_API_KEY
        sync: false
    
    # Disk for persistent storage (uploads, WhatsApp session)
    disk:
      name: sap-technologies-data
      mountPath: /opt/render/project/src/server
      sizeGB: 1 # Free tier allows 1GB

# Auto-deploy settings
autoDeploy: true
